const tbrBooks = [
  "Första boken i Windy City",
  "Första boken i Twisted-serien",
  "Onyx Storm",
  "Acotar",
  "Crescent City", 
  "The Ballad of Never After",
  "A Curse for True Love",
  "Lights Out",
  "Do Not Disturb - Freida McFadden",
  "Brain Damage - Freida McFadden",
  "The Pumpkin Spice Café", 
  "The Crash - Freida McFadden",
  "Under Your Scars",
  "A Love Letter to Whiskey",
  "You've Reached Sam", 
  "If He Had Been With Me",
  "The Things We Leave Unfinished",
  "The Serpent and the Wings of Night",
  "Releasing 10",
  "The Cruel Prince",
  "Quicksilver",
  "The Kiss of Deception",
  "The Mindfuck Series",
  "Första i The Windsor Serien",
  "Shatter Me",
  "Falling Kingdom - Morgan Rhodes",
  "Phantasma"
  
];

const baseSquares = [
  "Free pick",
  "Nyast på min TBR",
  "Romance",
  "Stand Alone",
  "Sports Romance",
  "Jämnt antal sidor",
  "Movie or TV",
  "5 star prediction",
  "People on the cover",
  "2 word title",
  "Spinner wheel",
  "No people on the cover",
  "En bok jag fått i present",
  "Sprayed edges",
  "Vampire",
  "Publicerad innan 2020",
  "Auto-buy author",
  "1 word title",
  "Grumpy sunshine",
  "Seasonal read",
  "Blommigt omslag",
  "Grönt omslag",
  "Continue a series",
  "Bok i duology",
  "Varulv",
  "Publicerad i år",
  "Age gap trope",
  "Stått länge på din TBR",
  "En bok jag undvikit",
  "Fantasy",
  "3 word title",
  "Color generator",
  "Fake dating",
  "Friends to lovers",
  "TBR jar",
  "400+ sidor",
  "Högst rankad på Goodreads",
  "500+ sidor",
  "Kortaste boken på din TBR",
  "Reverse page count",
  "Djur på omslaget",
  "Rött på omslaget",
  "Enemies to lovers",
  "Lila på omslaget",
  "Köp dig en ny bok",
  "Dual POV",
  "Längsta boken på din TBR",
  "Under 300 sidor",
  "Vitt på omslaget",
  "Ny författare",
  "6 ord eller mer i titeln",
  "Gult på omslaget",
  "Nummer i titeln",
  "Rosa på omslaget",
  "Svart på omslaget",
  "Dark romance",
  "Plats i titel",
  "Bok du köpt second hand",
  "4 word title",
  "Drakar",
  "Orange på omslaget",
  "Första boken i en serie",
  "Thriller",
  "Deckare",
  "Cowboy romance",
  "Romantasy",
  "En ny genre du inte läst förut",
  "En bok med snygg rygg",
  "En bok du köpt pga omslaget",
  "En bok du glömt att du äger",
  "Läs första boken i din TBR",
  "Läs sista boken du lade till",
  "En bok under 250 sidor",
  "En bok över 600 sidor",
  "En bok med ett namn i titeln",
  "En bok med en färg i titeln",
  "En bok med väder i storyn",
  "En bok som utspelar sig på vintern",
  "En bok som utspelar sig på sommaren",
  "En bok du skjutit upp länge",
  "En bok från en författare du aldrig läst",
  "En bok med en karaktär du tror du kommer älska",
  "En bok med dåliga reviews",
  "En bok med över 4.0 på Goodreads",
  "En bok som fått hype på TikTok",
  "En bok ingen pratar om",
  "En bok från din favoritgenre",
  "En bok från en genre du sällan läser",
  "En bok med magi",
  "En bok utan magi",
  "En bok med slow burn",
  "En bok med enemies to lovers",
  "En bok med friends to lovers",
  "En bok med fake dating",
  "En bok med one bed trope",
  "En bok med morally grey character",
  "En bok med found family",
  "En bok med stark kvinnlig huvudkaraktär",
  "En bok med flera POV",
  "En bok med korta kapitel",
  "En bok du kan läsa på en dag",
  "En bok du tror tar lång tid att läsa",
  "En bok med mörkt tema",
  "En bok som är feelgood",
  "En bok som får dig att gråta",
  "En bok som får dig att skratta",
  "En bok med plot twist",
  "En bok du tror är förutsägbar",
  "En bok med fint omslag",
  "En bok med fult omslag",
  "En bok med djur",
  "En bok utan människor på omslaget",
  "En bok du spontant väljer utan att tänka",
  "En bok du slumpgenerator väljer (Google!)",
  "En bok med kort titel",
  "En bok med lång titel",
  "En bok från en serie",
  "Fortsätt på en serie du pausat",
  "En bok du borde ha läst redan",
  "En bok du inte är sugen på (utmana dig!)"
];

const extras = [
  "Back 1",
  "Back 3",
  "Forward 2",
  "Forward 3",
  "TBR jar",
  "TBR jar",
  "Romance",
  "Romantasy",
  "Thriller",
  "Fantasy",
  "TBR jar",
  "TBR jar",
  "Free pick",
  "Skip (välj ny ruta)",
  "Byt bok mitt i läsningen",
  "Läs 50 sidor direkt",
];

const board = [...baseSquares, ...extras];
