const tbrBooks = [
  "Fourth Wing",
  "Iron Flame",
  "Powerless",
  "The Housemaid",
  "Never Lie",
  "Things We Never Got Over",
  "Twisted Love"
];

const baseSquares = [
  "Free pick",
  "Nyast på min TBR",
  "Romance",
  "Stand Alone",
  "Sports Romance",
  "Jämnt antal sidor",
  "Movie or TV",
  "5 star prediction",
  "People on the cover",
  "2 word title",
  "Spinner wheel",
  "No people on the cover",
  "En bok jag fått i present",
  "Sprayed edges",
  "Vampire",
  "Publicerad innan 2020",
  "Auto-buy author",
  "1 word title",
  "Grumpy sunshine",
  "Seasonal read",
  "Blommigt omslag",
  "Grönt omslag",
  "Continue a series",
  "Bok i duology",
  "Varulv",
  "Publicerad i år",
  "Age gap trope",
  "Stått länge på din TBR",
  "En bok jag undvikit",
  "Fantasy",
  "3 word title",
  "Color generator",
  "Fake dating",
  "Friends to lovers",
  "TBR jar",
  "400+ sidor",
  "Högst rankad på Goodreads",
  "500+ sidor",
  "Kortaste boken på din TBR",
  "Reverse page count",
  "Djur på omslaget",
  "Rött på omslaget",
  "Enemies to lovers",
  "Lila på omslaget",
  "Köp dig en ny bok",
  "Dual POV",
  "Längsta boken på din TBR",
  "Under 300 sidor",
  "Vitt på omslaget",
  "Ny författare",
  "6 ord eller mer i titeln",
  "Gult på omslaget",
  "Nummer i titeln",
  "Rosa på omslaget",
  "Svart på omslaget",
  "Dark romance",
  "Plats i titel",
  "Bok du köpt second hand",
  "4 word title",
  "Drakar",
  "Orange på omslaget",
  "Första boken i en serie",
  "Thriller",
  "Deckare",
  "Cowboy romance",
  "Romantasy",
  "En ny genre du inte läst förut"
];

const extras = [
  "Back 1",
  "Back 3",
  "Forward 2",
  "Forward 3",
  "TBR jar",
  "TBR jar",
  "Romance",
  "Romantasy",
  "Thriller",
  "Fantasy"
];

const board = [...baseSquares, ...extras];
